#!/usr/bin/env bash

# Install Script for replicating the installation.
# Collects all the customizing inputs at the start and installs everything.

shopt -s expand_aliases
SCRIPT_DIR=${BASH_SOURCE%/*}

source "$SCRIPT_DIR/00-utils.sh"
source "$SCRIPT_DIR/01-checks.sh"


# ==================== Validations ====================

echo
echo_title "Checking Prerequisites"

check_distro
check_arch
check_network
check_superuser
check_user

source "$SCRIPT_DIR/$distro/$arch/01-checks.sh"
source "$SCRIPT_DIR/$distro/$arch/02-packages.sh"
source "$SCRIPT_DIR/03-basic-steps.sh"
source "$SCRIPT_DIR/04-configure.sh"
source "$SCRIPT_DIR/05-bootstrap.sh"
source "$SCRIPT_DIR/06-finalize.sh"

not_founds=()
check_commands_availability kitty enquirer yadm xrandr xauth
check_pkg_availability xorg font-firacode mesa mesa-dri

#for pkg in "${not_founds[@]}"; do
#    install_pkg $pkg
#done

if [[ ! -n $DISPLAY ]]; then
    exec startx ${SCRIPT_DIR%/*}/.xinit-kitty sudo $SCRIPT_DIR/main
fi


# ==================== Basic Steps ====================

echo
echo_title "Performing some basic steps"

setup_sparse_checkout && setup_sparse_toggle_alias


# ==================== Configuration ====================

echo
echo_title "Configuration"

# configure_options || else specify config (kinda)
configure_global
configure_distro


# ==================== Bootstrap Execution ====================

echo
echo_title "Bootstrap"

setup_scripts
setup_nvchad
setup_screen_dpi
bootstrap_distro


# ==================== Finalize ====================

echo
echo_title "Finalize"

finalize

echo
echo_title "Done"
