[emacs-pcre]
src.git = "https://github.com/syohex/emacs-pcre"
src.branch = "master"
fetch.github = "syohex/emacs-pcre"

[emacs-chdir]
src.git = "https://github.com/Animeshz/emacs-chdir"
src.branch = "main"
fetch.github = "Animeshz/emacs-chdir"

[nix-fish]
# TODO: replace back to https://github.com/kidonng/nix.fish after PR #2 merged
src.git = "https://github.com/Animeshz/nix.fish"
src.branch = "master"
fetch.github = "Animeshz/nix.fish"

[nvm-fish]
src.git = "https://github.com/jorgebucaran/nvm.fish"
src.branch = "main"
fetch.github = "jorgebucaran/nvm.fish"

[phosphor-icons]
src.git = "https://github.com/phosphor-icons/web"
src.branch = "master"
fetch.github = "phosphor-icons/web"
