#!/bin/bash

cd "$HOME"

# bootstrap setup completely using Makefile
make bootstrap

# sparse checkout
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set '/*' '!README.md' '!UNLICENSE' '!Makefile'
yadm checkout --quiet

# adds aliases to fish, zsh & bash if they exists for hiding/unhiding README, UNLICENSE and Makefile.
dothide="alias dothide=\"yadm sparse-checkout set '/*' '!README.md' '!UNLICENSE' '!Makefile' && yadm checkout --quiet\""
dotunhide="alias dotunhide=\"yadm sparse-checkout set '/*' && yadm checkout --quiet\""

for config in "$HOME/.config/fish/config.fish" "$HOME/.zshrc" "$HOME/.bashrc"; do
    if [[ -f "$config" ]]; then
        grep -qxF "$dothide" "$config" || echo "$dothide" >> "$config"
        grep -qxF "$dotunhide" "$config" || echo "$dotunhide" >> "$config"
    fi
done

