# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs = {
    pname = "emacs";
    version = "a5fbfdef3713b39ab4663165064554077c2a8256";
    src = fetchFromGitHub {
      owner = "Animeshz";
      repo = ".emacs.d";
      rev = "a5fbfdef3713b39ab4663165064554077c2a8256";
      fetchSubmodules = false;
      sha256 = "sha256-h/qYUHOLXRBhG42TMx6XmZIFkplwBmj6PGDqvfIUS7w=";
    };
    date = "2023-04-01";
  };
}
