# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs-chdir = {
    pname = "emacs-chdir";
    version = "2de98712fd22b309e532c090cf2d6178496eb416";
    src = fetchFromGitHub {
      owner = "Animeshz";
      repo = "emacs-chdir";
      rev = "2de98712fd22b309e532c090cf2d6178496eb416";
      fetchSubmodules = false;
      sha256 = "sha256-hc4fh5kAxIZS0/luvvtUscxoY68IgrTaw6v5FJ+dpN0=";
    };
    date = "2023-06-15";
  };
  emacs-pcre = {
    pname = "emacs-pcre";
    version = "bc63431cff76dae6ccbff6470173c96ff037fae7";
    src = fetchFromGitHub {
      owner = "syohex";
      repo = "emacs-pcre";
      rev = "bc63431cff76dae6ccbff6470173c96ff037fae7";
      fetchSubmodules = false;
      sha256 = "sha256-5rluKQb0nJkKbU64EfnN1prvS/y5RL58ApUp79rEr0I=";
    };
    date = "2016-09-04";
  };
  nix-fish = {
    pname = "nix-fish";
    version = "a3256cf49846ee4de072c3a9af7a58aad4021693";
    src = fetchFromGitHub {
      owner = "Animeshz";
      repo = "nix.fish";
      rev = "a3256cf49846ee4de072c3a9af7a58aad4021693";
      fetchSubmodules = false;
      sha256 = "sha256-3M0dU30SrdjInp6MWEC0q7MTInrZNtY6Z9mhBw43PKs=";
    };
    date = "2024-01-03";
  };
  nvm-fish = {
    pname = "nvm-fish";
    version = "c69e5d1017b21bcfca8f42c93c7e89fff6141a8a";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "nvm.fish";
      rev = "c69e5d1017b21bcfca8f42c93c7e89fff6141a8a";
      fetchSubmodules = false;
      sha256 = "sha256-LV5NiHfg4JOrcjW7hAasUSukT43UBNXGPi1oZWPbnCA=";
    };
    date = "2023-04-30";
  };
  phosphor-icons = {
    pname = "phosphor-icons";
    version = "9c7fab62067cde499045d3d4c28dcd564cbe1194";
    src = fetchFromGitHub {
      owner = "phosphor-icons";
      repo = "web";
      rev = "9c7fab62067cde499045d3d4c28dcd564cbe1194";
      fetchSubmodules = false;
      sha256 = "sha256-KYjRVrdDZlg7ef99k4CGrnGUyvzrbdJeYLFgQPjQEag=";
    };
    date = "2024-02-12";
  };
}
