{ pkgs, lib, config, ... }:

with lib;
let
  cfg = config.display;
in
{
  options = {
    display.xorg.manage = mkEnableOption "Manage Xorg and display drivers or not";
  };

  config = {
    home.packages = with pkgs; mkIf cfg.xorg.manage [
      xorg.xorgserver
      xorg.xf86videointel
      xorg.xf86inputlibinput
      xorg.xf86inputevdev
      xorg.xinit
      xorg.xkill
      xorg.xrandr
      xorg.xrdb
      xorg.xsetroot
      dbus
      elogind
    ];

    home.file.".Xresources" = {
      executable = true;
      text = ''
        ! WARNING: This file is generated by home-manager.
        ! Do not edit it!

        Xft.dpi: ${toString (builtins.floor (96 * cfg.scale))}
        Xcursor.size: ${toString cfg.cursorSize}
      '';
    };

    # TODO (blocker): install opengl (otherwise no kitty): https://discourse.nixos.org/t/xorg-on-non-nixos/13455
    #
    # TODO (blocker): https://forums.gentoo.org/viewtopic-p-8690663.html?sid=ec4d4fc273ea1e6ccdbdd5cdacbe49ea
    #     either run elogind or compile pkgs.xorg.xorgserver with -Dsuid_wrapper that overwrites whole
    #     pkgs.xorg (instead of just pkgs.xorg.xorgserver) hence compiles all deps like herbstluftwm lmao
    #
    # That's why currently disabled using cfg.xorg.manage
    #
    # Requires "sudo usermod -aG input $(whoami)"
    home.file.".xserverrc" = mkIf cfg.xorg.manage {
      executable = true;
      text = ''
        #!/bin/sh
        if [ -z "$XDG_VTNR" ]; then
          exec ${pkgs.xorg.xorgserver}/bin/X -nolisten tcp -configdir ${config.xdg.configHome}/xorg.conf.d "$@"
        else
          exec ${pkgs.xorg.xorgserver}/bin/X -nolisten tcp -configdir ${config.xdg.configHome}/xorg.conf.d "$@" vt$XDG_VTNR
        fi
      '';
    };

    home.file.".xinitrc" = let
      # TODO: support commands for more than this
      windowManagerCommand = if cfg.windowManagers.herbstluftwm.enable then "${pkgs.herbstluftwm}/bin/herbstluftwm --locked" else "";
      barCommand = if cfg.bars.eww.enable then "${pkgs.eww}/bin/eww open topbar &" else "";
    in
    {
      executable = true;
      text = ''
        # WARNING: This file is generated by home-manager.
        # Do not edit it!

        # Syncs Xresources
        xrdb -merge ~/.Xresources &
        export GDK_DPI_SCALE=${toString cfg.scale}
        export QT_SCALE_FACTOR=${toString cfg.scale}
        export QT_AUTO_SCREEN_SCALE_FACTOR=0
        ${if cfg.hidpi.enable then "export QT_ENABLE_HIDPI_SCALING=1" else ""}

        # Wallpaper
        ${if cfg.wallpaper != null then "feh --bg-fill ${cfg.wallpaper}" else "xsetroot -solid '#5A8E3A'"} &

        # Topbar
        ${barCommand}

        # Key hold-repeat frequency
        xset r rate ${toString cfg.autoRepeat.delay} ${toString cfg.autoRepeat.rate}

        exec dbus-launch --exit-with-session ${windowManagerCommand}
      '';
    };

    xdg.configFile."xorg.conf.d/00-nix-module-paths.conf".text = ''
      Section "Files"
        ModulePath "${config.home.profileDirectory}/lib/xorg/modules/"
        FontPath "${config.home.profileDirectory}/share/fonts/"
        FontPath "${config.home.profileDirectory}/lib/X11/fonts/"
      EndSection
    '';

    xdg.configFile."xorg.conf.d/20-intel.conf".text = ''
      Section "Device"
        Identifier "Intel Graphics"
        Driver "intel"
      EndSection
    '';

    xdg.configFile."xorg.conf.d/40-libinput.conf".text = ''
      # Match on all types of devices but joysticks
      #
      # If you want to configure your devices, do not copy this file.
      # Instead, use a config snippet that contains something like this:
      #
      # Section "InputClass"
      #   Identifier "something or other"
      #   MatchDriver "libinput"
      #
      #   MatchIsTouchpad "on"
      #   ... other Match directives ...
      #   Option "someoption" "value"
      # EndSection
      #
      # This applies the option any libinput device also matched by the other
      # directives. See the xorg.conf(5) man page for more info on
      # matching devices.

      Section "InputClass"
              Identifier "libinput pointer catchall"
              MatchIsPointer "on"
              MatchDevicePath "/dev/input/event*"
              Driver "libinput"
      EndSection

      Section "InputClass"
              Identifier "libinput keyboard catchall"
              MatchIsKeyboard "on"
              MatchDevicePath "/dev/input/event*"
              Driver "libinput"
      EndSection

      Section "InputClass"
              Identifier "libinput touchpad catchall"
              Driver "libinput"
              MatchDevicePath "/dev/input/event*"
              MatchIsTouchpad "1"
              Option "AccelProfile" "adaptive"
      	Option "AccelSpeed" "0.4"
              Option "ClickMethod" "buttonareas"
              Option "DisableWhileTyping" "1"
              Option "HorizontalScrolling" "1"
              Option "LeftHanded" "0"
              Option "MiddleEmulation" "0"
              Option "NaturalScrolling" "1"
              Option "ScrollMethod" "twofinger"
              Option "SendEventsMode" "enabled"
              Option "Tapping" "1"
              Option "TappingDrag" "1"
              Option "TappingDragLock" "0"
      EndSection

      Section "InputClass"
              Identifier "libinput touchscreen catchall"
              MatchIsTouchscreen "on"
              MatchDevicePath "/dev/input/event*"
              Driver "libinput"
      EndSection

      Section "InputClass"
              Identifier "libinput tablet catchall"
              MatchIsTablet "on"
              MatchDevicePath "/dev/input/event*"
              Driver "libinput"
      EndSection
    '';

    # TODO: Get from shell script "gen-monitor-dpi 13.5 > ~/.config/xorg.conf.d/90-monitor.conf"
    xdg.configFile."xorg.conf.d/90-monitor.conf".text = ''
      Section "Monitor"
      	Identifier "eDP1"
      	DisplaySize 285 190
      EndSection
    '';
  };
}
