{ pkgs, lib, config, ... }:

with lib;
let
  cfg = config.preferences.display;
in
{
  options = {
    preferences.display.xorg.enableHost = mkEnableOption "Manage Xorg and display drivers on host or not";
  };

  config = mkIf cfg.enable {
    puppet.ral = mkIf cfg.xorg.enableHost {
      package.xorg = lib.home-manager.hm.dag.entryAnywhere { ensure = "present"; };
    };

    home.file.".Xresources" = {
      executable = true;
      text = ''
        ! WARNING: This file is generated by home-manager.
        ! Do not edit it!

        Xft.dpi: ${toString (builtins.floor (96 * cfg.scale))}
        Xcursor.size: ${toString cfg.cursorSize}
      '';
    };

    home.file.".xinitrc" = let
      # TODO: support commands for more than this
      windowManagerCommand = if cfg.windowManagers.herbstluftwm.enable then "${pkgs.herbstluftwm}/bin/herbstluftwm --locked" else "";
      barCommand = if cfg.bars.eww.enable then "${pkgs.eww}/bin/eww open topbar &" else "";
    in
    {
      executable = true;
      text = ''
        # WARNING: This file is generated by home-manager.
        # Do not edit it!

        # Syncs Xresources
        xrdb -merge ~/.Xresources &
        export GDK_DPI_SCALE=${toString cfg.scale}
        export QT_SCALE_FACTOR=${toString cfg.scale}
        export QT_AUTO_SCREEN_SCALE_FACTOR=0
        ${if cfg.hidpi.enable then "export QT_ENABLE_HIDPI_SCALING=1" else ""}

        # Wallpaper
        ${if cfg.wallpaper != null then "feh --bg-fill ${cfg.wallpaper}" else "xsetroot -solid '#5A8E3A'"} &

        # Topbar
        ${barCommand}

        # Key hold-repeat frequency
        xset r rate ${toString cfg.autoRepeat.delay} ${toString cfg.autoRepeat.rate}

        exec dbus-launch --exit-with-session ${windowManagerCommand}
      '';
    };

    # This is not working atm
    # environment.etc."X11/xorg.conf.d/00-nix-module-paths.conf".text = ''
    #   Section "Files"
    #     ModulePath "${config.home.profileDirectory}/lib/xorg/modules/"
    #     FontPath "${config.home.profileDirectory}/share/fonts/"
    #     FontPath "${config.home.profileDirectory}/lib/X11/fonts/"
    #   EndSection
    # '';

    environment.etc."X11/xorg.conf.d/20-intel.conf".text = ''
      Section "Device"
        Identifier "Intel Graphics"
        Driver "intel"
      EndSection
    '';

    environment.etc."X11/xorg.conf.d/40-libinput.conf".text = ''
      # Match on all types of devices but joysticks
      #
      # If you want to configure your devices, do not copy this file.
      # Instead, use a config snippet that contains something like this:
      #
      # Section "InputClass"
      #   Identifier "something or other"
      #   MatchDriver "libinput"
      #
      #   MatchIsTouchpad "on"
      #   ... other Match directives ...
      #   Option "someoption" "value"
      # EndSection
      #
      # This applies the option any libinput device also matched by the other
      # directives. See the xorg.conf(5) man page for more info on
      # matching devices.

      Section "InputClass"
              Identifier "libinput pointer catchall"
              MatchIsPointer "on"
              MatchDevicePath "/dev/input/event*"
              Driver "libinput"
      EndSection

      Section "InputClass"
              Identifier "libinput keyboard catchall"
              MatchIsKeyboard "on"
              MatchDevicePath "/dev/input/event*"
              Driver "libinput"
      EndSection

      Section "InputClass"
              Identifier "libinput touchpad catchall"
              Driver "libinput"
              MatchDevicePath "/dev/input/event*"
              MatchIsTouchpad "1"
              Option "AccelProfile" "adaptive"
      	Option "AccelSpeed" "0.4"
              Option "ClickMethod" "buttonareas"
              Option "DisableWhileTyping" "1"
              Option "HorizontalScrolling" "1"
              Option "LeftHanded" "0"
              Option "MiddleEmulation" "0"
              Option "NaturalScrolling" "1"
              Option "ScrollMethod" "twofinger"
              Option "SendEventsMode" "enabled"
              Option "Tapping" "1"
              Option "TappingDrag" "1"
              Option "TappingDragLock" "0"
      EndSection

      Section "InputClass"
              Identifier "libinput touchscreen catchall"
              MatchIsTouchscreen "on"
              MatchDevicePath "/dev/input/event*"
              Driver "libinput"
      EndSection

      Section "InputClass"
              Identifier "libinput tablet catchall"
              MatchIsTablet "on"
              MatchDevicePath "/dev/input/event*"
              Driver "libinput"
      EndSection
    '';
  };
}
